server:
  port: 8777

endpoint: oss-cn-beijing.aliyuncs.com

spring:
  freemarker:
    suffix: .html
    cache: false
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      # 单个文件大小
      max-file-size: 10MB
      # 总文件大小
      max-request-size: 10MB
      # 临时文件路径
      location: D://mysoft
